# Generated by Django 2.2.16 on 2022-09-02 05:41

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(db_index=True, validators=[api.validators.validate_year], verbose_name='Год создания'),
        ),
    ]
