# Generated by Django 2.2.16 on 2022-08-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Зарегистрированный пользователь', 'Зарегистрированный пользователь'), ('Модератор', 'Модератор'), ('Администратор', 'Администратор')], default='user', max_length=30, verbose_name='Роль пользователя'),
        ),
    ]
