# Generated by Django 2.2.16 on 2022-08-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220826_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Пользователь', 'Пользователь'), ('Модератор', 'Модератор'), ('Администратор', 'Администратор')], default='user', max_length=30, verbose_name='Роль пользователя'),
        ),
    ]
