# Generated by Django 2.2.16 on 2022-08-29 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220825_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='categories.Title'),
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
